### ISSUE TITLE
大佬关于某站的适配

### ISSUE THREAD

**Issue by iovejieba** [hsuyelin/nas-tools-sites#4]
从隔壁大佬那边找到了一部分的json但貌似直接套少... 我把torrent源码转存了，另外还有一个json，可能对比下工程量就少一些，我拼了下没成功....
https://www.123pan.com/s/bcsSVv-ReBwv.html

**Comment by hsuyelin** [comment]
感谢，抽空看看，这两天在忙私事，忙完了再补遗留的东西

**Comment by iovejieba** [comment]
> 感谢，抽空看看，这两天在忙私事，忙完了再补遗留的东西

好咧大佬，感谢 我这抄抄补补  缺东西 翻代码没太抄明白 比较尴尬

**Comment by iovejieba** [comment]
大佬 get 搜索没啥问题 返回数据报错
它请求的搜索地址没问题 返回数据报错

> <html>
<body>


2023-08-31 16:49:46 | stdout | 2023-09-01 00:49:46,156 WARNING: 【Spider】错误：exoticaz Expected selector, got <DELIM '&' at 14>
-- | -- | --
2023-08-31 16:49:46 | stdout |  
2023-08-31 16:49:46 | stdout |  
2023-08-31 16:49:46 | stdout | cssselect.parser.SelectorSyntaxError: Expected selector, got <DELIM '&' at 14>
2023-08-31 16:49:46 | stdout | raise SelectorSyntaxError("Expected selector, got %s" % (peek,))
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 700, in parse_simple_selector
2023-08-31 16:49:46 | stdout | next_selector, pseudo_element = parse_simple_selector(stream)
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 585, in parse_selector
2023-08-31 16:49:46 | stdout | yield Selector(*parse_selector(stream))
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 558, in parse_selector_group
2023-08-31 16:49:46 | stdout | return list(parse_selector_group(stream))
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 543, in parse
2023-08-31 16:49:46 | stdout | for selector in parse(css)
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/xpath.py", line 224, in css_to_xpath
2023-08-31 16:49:46 | stdout | return self._translator.css_to_xpath(selector, prefix)
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 238, in _css_to_xpath
2023-08-31 16:49:46 | stdout | xpath = self._css_to_xpath(selector)
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 227, in __init__
2023-08-31 16:49:46 | stdout | return self.__class__(*args, **kwargs)
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 242, in _copy
2023-08-31 16:49:46 | stdout | result = self._copy(*args, parent=self, **kwargs)
2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 256, in __call__
2023-08-31 16:49:46 | stdout | for torn in html_doc(torrents_selector):
2023-08-31 16:49:46 | stdout | File "/nas-tools/app/indexer/client/_spider.py", line 654, in parse
2023-08-31 16:49:46 | stdout | Traceback (most recent call last):
2023-08-31 16:49:46 | stdout | Callstack:
2023-08-31 16:49:46 | stdout | Exception: Expected selector, got <DELIM '&' at 14>


</body>
</html>

**Comment by hsuyelin** [comment]
那就需要在改一下，他那个不适合
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月01日 00:55 |
| 收件人 | hsuyelin/nas-tools-sites ***@***.***> |
| 抄送人 | hsuyelin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [hsuyelin/nas-tools-sites] 大佬关于某站的适配 (Issue #4) |

大佬 get 搜索没啥问题 返回数据报错
它请求的搜索地址没问题 返回数据报错

| 2023-08-31 16:49:46 | stdout | 2023-09-01 00:49:46,156 WARNING: 【Spider】错误：exoticaz Expected selector, got <DELIM '&' at 14> |
| 2023-08-31 16:49:46 | stdout |   |
| 2023-08-31 16:49:46 | stdout |   |
| 2023-08-31 16:49:46 | stdout | cssselect.parser.SelectorSyntaxError: Expected selector, got <DELIM '&' at 14> |
| 2023-08-31 16:49:46 | stdout | raise SelectorSyntaxError("Expected selector, got %s" % (peek,)) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 700, in parse_simple_selector |
| 2023-08-31 16:49:46 | stdout | next_selector, pseudo_element = parse_simple_selector(stream) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 585, in parse_selector |
| 2023-08-31 16:49:46 | stdout | yield Selector(*parse_selector(stream)) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 558, in parse_selector_group |
| 2023-08-31 16:49:46 | stdout | return list(parse_selector_group(stream)) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/parser.py", line 543, in parse |
| 2023-08-31 16:49:46 | stdout | for selector in parse(css) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/cssselect/xpath.py", line 224, in css_to_xpath |
| 2023-08-31 16:49:46 | stdout | return self._translator.css_to_xpath(selector, prefix) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 238, in _css_to_xpath |
| 2023-08-31 16:49:46 | stdout | xpath = self._css_to_xpath(selector) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 227, in init |
| 2023-08-31 16:49:46 | stdout | return self.class(*args, **kwargs) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 242, in _copy |
| 2023-08-31 16:49:46 | stdout | result = self._copy(*args, parent=self, **kwargs) |
| 2023-08-31 16:49:46 | stdout | File "/usr/local/lib/python3.10/site-packages/pyquery/pyquery.py", line 256, in call |
| 2023-08-31 16:49:46 | stdout | for torn in html_doc(torrents_selector): |
| 2023-08-31 16:49:46 | stdout | File "/nas-tools/app/indexer/client/_spider.py", line 654, in parse |
| 2023-08-31 16:49:46 | stdout | Traceback (most recent call last): |
| 2023-08-31 16:49:46 | stdout | Callstack: |
| 2023-08-31 16:49:46 | stdout | Exception: Expected selector, got <DELIM '&' at 14> |

**Comment by iovejieba** [comment]
> DELIM '&' at 14

大佬我把搜索之后的list列表的源码保存了下，有时间可以看下是否有帮助  
https://www.123pan.com/s/bcsSVv-PLBwv.html

**Comment by hsuyelin** [comment]
> > DELIM '&' at 14
> 
> 大佬我把搜索之后的list列表的源码保存了下，有时间可以看下是否有帮助 https://www.123pan.com/s/bcsSVv-PLBwv.html

好嘞。抽空瞅一瞅

**Comment by hsuyelin** [comment]
> > DELIM '&' at 14
> 
> 大佬我把搜索之后的list列表的源码保存了下，有时间可以看下是否有帮助 https://www.123pan.com/s/bcsSVv-PLBwv.html

原来瑟瑟站

**Comment by iovejieba** [comment]
> > > DELIM '&' at 14
> > 
> > 
> > 大佬我把搜索之后的list列表的源码保存了下，有时间可以看下是否有帮助 https://www.123pan.com/s/bcsSVv-PLBwv.html
> 
> 原来瑟瑟站

大佬此言差异 这明明是艺术观赏
